// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

import '../config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if (AppConfig.buildType == EnvironmentType.dev) {
          return androidDev;
        }
        return androidStg;

    /*  case TargetPlatform.iOS:
        if (AppConfig.buildType == EnvironmentType.dev) {
          return iosDev;
        }
        return iosProd;*/

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyBfZFhdKeDPFPoa9Axgv_FAqJFL6RHsEmc',
    appId: '1:1023692387320:android:11b54f546cfe4893559c0d',
    messagingSenderId: '1023692387320',
    projectId: 'imageapp-62f19',
  );

  ///ToDo: change info
  static const FirebaseOptions androidStg = FirebaseOptions(
    apiKey: 'AIzaSyBDjXkzRl-kKFZ4n03BpTB5lZZdMW_Yg0M',
    appId: '1:510280957614:android:a7a67e655dc5cd93eb373f',
    messagingSenderId: '510280957614',
    projectId: 'imageapp2-912cf',
    storageBucket: 'imageapp2-912cf.firebasestorage.app',
  );

 /* ///ToDo: change info
  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyA-NV-sMlnjQAGQDJ263P76Ahu8pevawMU',
    appId: '1:207308719630:ios:4d64cf3e31eaa17f4f1e5f',
    messagingSenderId: '207308719630',
    projectId: 'care-sweet-staging',
    iosBundleId: 'net.caresweet.staging',
  );*/

  ///ToDo: change info
  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyBCSN46ODUhgZYoNc555ASfZKvqRFqv-0s',
    appId: '1:510280957614:ios:94f7da032e5c598aeb373f',
    messagingSenderId: '510280957614',
    projectId: 'imageapp2-912cf',
    storageBucket: 'imageapp2-912cf.firebasestorage.app',
    iosBundleId: 'com.example.bai1',
  );

  Future<void> getAppConfigCurrent() async {
    await AppConfig.current();
  }
}
